services:

  db:
    image: postgres
    container_name: pg_edu

    ports:
      - "5432:5432"
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}