"""add cascade deletion for Subject and Teacher relation

Revision ID: 6472636e6dca
Revises: ca91166937cf
Create Date: 2026-04-19 01:34:39.137534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6472636e6dca'
down_revision: Union[str, Sequence[str], None] = 'ca91166937cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subjects_teacher_id_fkey'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('subjects_teacher_id_fkey'), 'subjects', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
