"""Grade grad type to Integer fix

Revision ID: f65b88f68c0a
Revises: 64cb64892713
Create Date: 2026-04-19 02:46:26.618816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f65b88f68c0a"
down_revision: Union[str, Sequence[str], None] = "64cb64892713"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "grades",
        "grade",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="grade::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "grades",
        "grade",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
